### ISSUE TITLE
New Coinbase exchange

### ISSUE THREAD

**Issue by zholmes1** [timmolter/XChange#839]
I'm sure we've all heard by now that Coinbase is getting ready to launch their own regulated exchange in the US.

Here is the documentation for their API: https://docs.exchange.coinbase.com/#get-an-account

Anyone willing to work with me on this? I can do all the DTOs/package set-up if someone else will implement the logic.

**Comment by tmlee** [comment]
@zholmes1 @timmolter I wonder has anybody started working on this one? We are looking to use the public market data (ticker). If no one has initiated, we might consider working on the public market data (ticker) for the Coinbase Exchange.

**Comment by timmolter** [comment]
As far as I know, no one is working on it.

**Comment by zholmes1** [comment]
I haven't started working on it. Mostly because I don't know what to name
it. CoinbaseExchangeExchange?

**Comment by tmlee** [comment]
How about CoinbaseXExchange?

**Comment by zholmes1** [comment]
Sounds good to me.

**Comment by tmlee** [comment]
@zholmes1 Are you planning to work on it? Shall we wait for the good news? :smile:

**Comment by zholmes1** [comment]
If you do the framework and implement the ticker, I'll do the order book
and trades. I can't do trading right now since it's not supported in my
state yet. Maybe if we do the public implementation someone else will do
the private implementation.

**Comment by yingzhe** [comment]
@tmlee and I will start working on the public implementation of CoinBase market data

**Comment by yingzhe** [comment]
Should I create a new Maven module (and call it something like xchange-coinbasex), or should I make the additions to the existing xchange-coinbase module?

**Comment by timmolter** [comment]
@yingzhe probably a new module. Are there any common DTOs between the two implementations? If np then definitely a new module

**Comment by yingzhe** [comment]
@zholmes1 @tmlee Coinbase exchange module (xchange-coinbaseex) has just been added

**Comment by jheusser** [comment]
+1

**Comment by jheusser** [comment]
@yingzhe btw are you planning on adding trading and account functionality any time soon?

**Comment by yingzhe** [comment]
Nope, I would not have much time in the near future to work on this.

**Comment by radumiron** [comment]
I would want to extend the current code by adding support for more operations, like:
- exchange symbols loaded from exchange
- trade history
- recent filled orders

The associated pull request is #989

**Comment by timmolter** [comment]
done.

**Comment by btiernay** [comment]
Curious as to why websocket support was not added. Maybe it didn't exist at the time? Any reason why XChange still doesn't support it?
